### ISSUE TITLE
More permissive license?

### ISSUE THREAD

**Issue by zeldigas** [titov-vv/dlsg-file#1]
Would be great to have an option to use this code under more permissive license, like apache 2.

As an alternative - to have internal structure description that can be used implementing reader in other languages

**Comment by titov-vv** [comment]
Hi,
I'm not very familiar with license types. Frankly, I don't remember why this one was chosen (probably as copy-paste from another project where I planned to use this module and had been restricted with GPL usage)
I'll review the choice in coming days and update you.

**Comment by titov-vv** [comment]
License was changed to MIT

**Comment by zeldigas** [comment]
Great, thank you! I'll try to build some spec to ease implementation in other programming languages.

**Comment by titov-vv** [comment]
You are welcome.
I may give some comments about format if required... (my mail is available in jal repo) - just don't have time to put it here in a readable form. The most important one - it isn't fixed and they tend to change it every year.
